In [ ]:
import numpy as np
from scipy.stats import entropy
import pandas as pd

NameError: name 'im' is not defined

In [28]:
inside = np.array([np.nan, np.nan, np.nan, 1, 2, 3, 4, 1, 0, 0, 0, 0])
# inside = inside / inside.sum()
inside

array([nan, nan, nan,  1.,  2.,  3.,  4.,  1.,  0.,  0.,  0.,  0.])

In [30]:
(entropy(inside, nan_policy='omit'))

np.float64(1.4681399390162087)

In [23]:
inside = np.array([10, 3, 45, 15, 6, 8])
volume = 8

density = inside / volume

rel_inside = inside / inside.sum()
rel_density = density / density.sum()

print(rel_inside)
print(rel_density)

[0.11494253 0.03448276 0.51724138 0.17241379 0.06896552 0.09195402]
[0.11494253 0.03448276 0.51724138 0.17241379 0.06896552 0.09195402]


In [27]:
z_max = 10.5
z_bin_size = 1

bins = np.arange(0, z_max + z_bin_size, z_bin_size)
bins

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])